// src/layouts/BaseLayout/@Components/Navigation/Navigation.tsx
import { useMemo } from 'react';
import { useLocation, NavLink } from 'react-router-dom';
import Routes from 'routes';
import Avatar from 'layouts/BaseLayout/@Components/Avatar';
import './Navigation.scss';

const Navigation = () => {
  /**
   * Get the current location object from the hook.
   *
   * @var {Object}
   */
  const location = useLocation();

  const doTheme = (arg: string): void => {
    document.body.className = arg;
  };

  /**
   * Add the active class to the navigation item that matches
   * the current route.
   *
   * @param {String} path
   * @return {String}
   */
  const isActive = (path: string) => {
    return (location.pathname === path ? 'is-active' : '');
  };

  /**
   * Loop through all available routes but filter out the
   * base route item.
   *
   * @return {Object}
   */
  const navigation = Routes
    .filter(item => item.path !== '/')
    .map((item, key) => {
      return (
        <NavLink
          className={`navbar-item ${isActive(item.path)}`}
          key={key}
          to={`${item.path}`}
        >
          {item.name}
        </NavLink>
      );
    }
  );

   const light = useMemo(() => {
    return {
      width: '20px',
      height: '20px',
      marginTop: '15px',
      marginLeft: '15px',
      padding: '5px',
      backgroundColor: '#fff',
      cursor: 'pointer',
      borderStyle: 'solid',
      borderWidth: '2px',
      borderColor: '#ccc',
      WebkitBorderRadius: 50,
      MozBorderRadius: 50,
      borderRadius: 50,
    };
  }, []);

  const dark = useMemo(() => {
    return {
      width: '20px',
      height: '20px',
      marginTop: '15px',
      marginLeft: '15px',
      padding: '5px',
      backgroundColor: '#000',
      cursor: 'pointer',
      borderStyle: 'solid',
      borderWidth: '2px',
      borderColor: '#ccc',
      WebkitBorderRadius: 50,
      MozBorderRadius: 50,
      borderRadius: 50,
    };
  }, []);

  return (
    <div className="hero-head">
    <nav className="navbar">
      <div className="navbar-brand">
        <Avatar/>
      </div>
      <div className="navbar-menu is-capitalized">
        <div className="navbar-start">
          {navigation}
        </div>

        <div className="navbar-end">
          <div
            className="navbar-item"
            style={light}
            onClick={doTheme.bind(this, 'light')}
          />
          <div
            className="navbar-item"
            style={dark}
            onClick={doTheme.bind(this, 'dark')}
          />
        </div>
      </div>
    </nav>
  </div>
  );
};

export default Navigation;

// src/layouts/BaseLayout/@Components/Navigation/Navigation.vue
<script lang="ts">
/**
 * Modules
 */
import { Options, Vue } from 'vue-class-component';

/**
 * Components
 */
import Avatar from '../Avatar';

@Options({
  components: {
    Avatar,
  },
})

export default class Navigation extends Vue {
  /**
   * The component name.
   *
   * @var {String}
   */
  public name = 'Navigation';

  /**
   * Get all available routes other than Home.
   *
   * @return {String[]}
   */
  get routes(): string[] {
    return (this.$router as any)
      .options.routes
      .filter(route => route.name !== 'Home')
    ;
  }

  /**
   * Get the route styles and add the is-active class
   * if the route is indeed the current.
   *
   * @param {String} route
   * @return {String}
   */
  styles(route: string): string {
    return (`navbar-item ${this.$route.name === route ? 'is-active' : ''}`);
  }
}
</script>

<template>
  <div class="hero-head">
    <nav class="navbar">
      <div class="navbar-brand">
        <Avatar/>
      </div>

      <div class="navbar-menu is-capitalized">
        <div class="navbar-start">
          <RouterLink
            v-for="({ path, name }, key) in routes"
            :key="key"
            :class="styles(name)"
            v-text="name"
            :to="path"
          />
        </div>

        <!--
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="theme white"/>
          </div>
          <div class="navbar-item">
            <div class="theme blue"/>
          </div>
          <div class="navbar-item">
            <div class="theme black"/>
          </div>
        </div>
        -->
      </div>
    </nav>
  </div>
</template>

<style lang="scss" scoped>
@import '@/assets/scss/config/mixins/_all';

.hero-head {
  .navbar {
    .navbar-menu {
      margin-left: 10px !important;
      justify-content: left;

      .navbar-start {
        .navbar-item {
          margin-top: 10px;
        }

        a {
          color: #6D6D6D;
          font-size: 12px;
          font-weight: 600 !important;
          text-transform: uppercase;
          @include color-transition;

          &:hover {
            background: none;
            color: #000000;
          }

          &.is-active {
            background: none;
            color: #3090C7;
          }
        }
      }

      .navbar-end {
        margin-right: 20px;

        .navbar-item {
          padding: 0 15px 0 0;

          .theme {
            height: 15px;
            width: 15px;
            cursor: pointer;
            border-radius: 50%;

            &.white {
              background: #ffffff;
              border: 1px solid #6D6D6D;
            }

            &.blue {
              background: #3090C7;
              border: 1px solid #3090C7;
            }

            &.black {
              background: #000000;
              border: 1px solid #000000;
            }
          }
        }
      }
    }
  }
}
</style>
