// src/views/Hobbies/Hobbies.tsx
import BaseLayout from 'layouts/BaseLayout';

const Hobbies = () => {
  return (
    <BaseLayout>
      <div className="columns">
        <div className="column">
          <h2><span className="has-text-black">H</span>obbies</h2>
          <p>So, when I'm not coding or thinking about tech there are many things that I enjoy doing in my free time. Everyone needs to disconnect.</p>
          <p><strong>Playing Games.</strong> Of course videos games but not always. Losing yourself in a board game with my family is by far the best of the best.</p>
          <p><strong>House work.</strong> That's right I actually enjoy knocking out honey do lists with some home improvements. So much that I did all the designing, planning and construction of our unfinished basement.</p>
          <p><strong>Making beer.</strong> A new hobbie that I recently started is learning how to properly make homemade beer. It's such a pretty relaxing thing to do where it has become a personal goal to open up a micro brewery.</p>
          <p><strong>Music.</strong> Whether I'm listening or playing it, music will always have that special place in my heart.</p>
          <p><strong>Shooting.</strong> Wouldn't call myself a gun nut but I certainly do enjoy heading out to a range and practicing and continuing to learn and improve upon the skill of target shooting.</p>
        </div>
      </div>
    </BaseLayout>
  );
};

export default Hobbies;

// src/views/Hobbies/Hobbies.vue
<script lang="ts">
/**
 * Modules
 */
import { defineComponent } from 'vue';

export default defineComponent({
  setup() {
    return {};
  }
});
</script>

<template>
  <BaseLayout>
    <template v-slot:content>
      <div class="columns">
        <div class="column">
          <h2><span class="has-text-black">H</span>obbies</h2>
          <p>So, when I'm not coding or thinking about tech there are many things that I enjoy doing in my free time. Everyone needs to disconnect.</p>
          <p><strong>Playing Games.</strong> Of course videos games but not always. Losing yourself in a board game with my family is by far the best of the best.</p>
          <p><strong>House work.</strong> That's right I actually enjoy knocking out honey do lists with some home improvements. So much that I did all the designing, planning and construction of our unfinished basement.</p>
          <p><strong>Making beer.</strong> A new hobbie that I recently started is learning how to properly make homemade beer. It's such a pretty relaxing thing to do where it has become a personal goal to open up a micro brewery.</p>
          <p><strong>Music.</strong> Whether I'm listening or playing it, music will always have that special place in my heart.</p>
          <p><strong>Shooting.</strong> Wouldn't call myself a gun nut but I certainly do enjoy heading out to a range and practicing and continuing to learn and improve upon the skill of target shooting.</p>
        </div>
      </div>
    </template>
  </BaseLayout>
</template>
