// src/layouts/BaseLayout/BaseLayout.vue
<script lang="ts">
/**
 * Modules
 */
import { Options, Vue } from 'vue-class-component';

/**
 * Components
 */
import Navigation from './@Components/Navigation';
import Particles from './@Components/Particles';

@Options({
  components: {
    Navigation,
    Particles,
  },
})

export default class BaseLayout extends Vue {
  /**
   * The component name.
   *
   * @var {String}
   */
  public name = 'BaseLayout';
}
</script>

<template>
  <Particles/>
  <section class="hero is-fullheight is-unselectable">
    <Navigation/>
    <div class="hero-body">
      <div class="container">
        <slot name="content"/>
      </div>
    </div>
  </section>
</template>

<style lang="scss" scoped>
.particles {
  position: absolute;
  top: 0;
  left: 0;
  height: 100vh;
  width: 100%;
}

.hero {
  background: none;

  .hero-body {
    .container {
      margin: -100px 200px 0 200px;
    }
  }
}
</style>

// src/layouts/BaseLayout/BaseLayout.tsx
import { FC } from "react";
import Navigation from './@Components/Navigation';
import Particles from './@Components/Particles';
import './BaseLayout.scss';

interface Props {}

const BaseLayout: FC<Props> = ({ children }) => {
  return (
    <div>
      <Particles/>
      <section className="hero is-unselectable">
        <Navigation/>
        <div className="hero-body">
          <div className="container is-fullheight">
            {children}
          </div>
        </div>
      </section>
    </div>
  );
};

export default BaseLayout;
