// src/layouts/BaseLayout/@Components/Particles/Particles.tsx
import { useEffect } from 'react';
import ParticlesJSConfig from 'config/particlesjs';
require('particles.js');

const Particles = () => {
  /**
   * Initialize the particles using the hook.
   *
   * @return {Void}
   */
  useEffect(() => {
    const windowObject = (window as any);
    windowObject.pJSDom = [];
    windowObject.particlesJS('particles', ParticlesJSConfig);
    return () => {};
  }, []);

  return (
    <div
      className="particles"
      id="particles"
    />
  );
};

export default Particles;

// src/layouts/BaseLayout/@Components/Particles/Particles.vue
<script lang="ts">
/**
 * Modules
 */
import { Options, Vue } from 'vue-class-component';
require('particles.js');

/**
 * Config
 */
import config from '@/config/particlesjs';

@Options({})

export default class Particles extends Vue {
  /**
   * The component name.
   *
   * @var {String}
   */
  public name = 'Particles';

  /**
   * The mounted lifecycle method.
   *
   * @return {Void}
   */
  mounted(): void {
    const windowObject = (window as any);
    windowObject.pJSDom = [];
    windowObject.particlesJS('particles', config);
  }
}
</script>

<template>
  <div
    class="particles"
    id="particles"
  />
</template>
